version: "3.8"
services:

    api:
        container_name: nest_api
        build: .
        ports:
            - 3000:3000
        volumes:
            - .:/home/api
        depends_on:
            - mysql-development
            - mongodb
        links:
            - mongodb
            - mysql-development

    mongodb:
        image : mongo:latest
        container_name: mongodb
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass12345
    
    mysql-development:
        image: mysql:8.0.17
        environment:
            MYSQL_ROOT_PASSWORD: pass12345
            MYSQL_DATABASE: development
        ports:
            - 3306:3306